"""Protocol interfaces (ports). Pure abstractions, 0 implementations."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol, runtime_checkable

from CLI_agent_memory.domain.types import (
    CommandResult,
    ContextPack,
    Decision,
    LLMResponse,
    Memory,
    Message,
    Plan,
    ThinkingResult,
    VaultEntry,
)


@runtime_checkable
class MemoryProtocol(Protocol):
    async def recall(self, query: str, max_tokens: int = 4000) -> ContextPack: ...
    async def store(self, event_type: str, content: str, tags: list[str] | None = None) -> str: ...
    async def ingest(self, event_type: str, content: str) -> None: ...
    async def search(self, query: str, limit: int = 10) -> list[Memory]: ...
    async def list(self, tags: list[str] | None = None, limit: int = 50) -> list[Memory]: ...


@runtime_checkable
class ThinkingProtocol(Protocol):
    async def think(self, problem: str, depth: int = 5) -> ThinkingResult: ...
    async def get_session(self, session_id: str) -> ThinkingResult | None: ...


@runtime_checkable
class EngramProtocol(Protocol):
    async def save_decision(self, title: str, body: str, tags: list[str] | None = None) -> str: ...
    async def search_decisions(self, query: str) -> list[Decision]: ...
    async def save_entity(self, name: str, kind: str, data: dict) -> str: ...
    async def search_entities(self, query: str) -> list[dict]: ...


@runtime_checkable
class PlanningProtocol(Protocol):
    async def create_plan(self, goal: str, context: str) -> Plan: ...
    async def get_plan(self, plan_id: str) -> Plan | None: ...


@runtime_checkable
class ConversationProtocol(Protocol):
    async def save(self, thread_id: str, messages: list[dict], summary: str) -> str: ...
    async def search(self, query: str) -> list[dict]: ...


@runtime_checkable
class VaultProtocol(Protocol):
    async def write(self, folder: str, filename: str, content: str) -> VaultEntry: ...
    async def read(self, folder: str, filename: str) -> str | None: ...
    async def search(self, query: str) -> list[VaultEntry]: ...
    async def list_entries(self, folder: str = "") -> list[VaultEntry]: ...
    async def append(self, folder: str, filename: str, content: str) -> None: ...


@runtime_checkable
class WorkspaceProtocol(Protocol):
    def create(self, branch_name: str, base_ref: str = "HEAD") -> Path: ...
    def remove(self, branch_name: str, force: bool = False) -> bool: ...
    def run_command(self, worktree_path: Path, command: str) -> CommandResult: ...
    def read_file(self, worktree_path: Path, file_path: str) -> str | None: ...
    def write_file(self, worktree_path: Path, file_path: str, content: str) -> None: ...
    def list_files(self, worktree_path: Path, pattern: str = "**/*.py") -> list[str]: ...


@runtime_checkable
class LLMClient(Protocol):
    async def generate(
        self,
        prompt: str,
        history: list[Message],
        temperature: float = 0.1,
        max_tokens: int = 4096,
    ) -> LLMResponse: ...
    def is_available(self) -> bool: ...
